
# Análise de relação das familias envolvidas na dança dos dragões da série House of the dragon

O projeto foi desenvolvido para a avaliação final da disciplina de Análise de Algoritmos. São utilizadas as bibliotecas networkx, numpy e matplotlib para criar e visualizar grafos que representam as relações entre diferentes núcleos familiares envolvidos na Dança dos Dragões (uma guerra que ocorreu no universo ficticio de game of thrones). O projeto permite análisar alianças, neutralidade e inimizades que existiam entre as familias utilizando um grafo simetrico onde as arestas tem cores diferentes para representar qual o tipo de relação entre os nós (familias).

## Funcionalidades
Adicionar conexões entre as famílias, visualizar as relações em um grafo, inserção de dados (familias e relações0).

## Funcionalidades futuras
Remover relações; implementar tratamento de exceções; melhorar a análise de fluxo;implementação de um dicionário com famílias importantes para facilitar a seleção; desenvolvimento de uma GUI.

## Pré requisitos
Bibliotecas matplotlib, networkx e numpy instaladas.

## Visualização do grafo
Após adicionar as conexões o grafo será exibido usando matplotlib (pyplot). As cores dos nós são determinadas pela família colocada, se a familia for targaryen os nós serão pretos, se for hightower os nós serão verdes, se a familia não for nenhuma das duas os nós serão azuis.


## Autores
- Shelda Azevedo
- Isabella Monte
- Antônio Palmeira




- [@SATRbytes](https://github.com/SATRbytes)




## Referência

 - [Analise de redes sociais com python](https://www.youtube.com/watch?v=tNeL4kNcJ94)
 - [Documentação networkx](https://networkx.org/documentation/stable/index.html)
 - [Grafos em Python](https://www.kaggle.com/code/flaviagg/grafos-em-python)
 - [Criando algoritmo de pesquisa em largura BFS] (https://dev.to/antiduhring/criando-um-algoritmo-de-pesquisa-em-largura-em-grafos-3af3)

