# -*- coding: utf-8 -*-
"""casas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18dxqN0PgHlOHHjNAdgSeOcuySU2eni7s
"""

#casas do grafo de alinhamento

team_black = [
    "Casa Velaryon", "Casa Stark", "Casa Arryn", "Casa Greyjoy", "Casa Frey",
    "Casa Tully", "Casa Bar Emmon", "Casa Beesbury", "Casa Bigglestone",
    "Casa Blackwood", "Casa Borrell", "Casa Bracken", "Casa Brune de Brownhollow",
    "Casa Brune de Dyre Den", "Casa Buckler", "Casa Byrch", "Casa Cerwyn",
    "Casa Celtigar", "Casa Caswell", "Casa Costayne", "Casa Chambers",
    "Casa Charlton", "Casa Corbay", "Casa Crabb", "Casa Darklyn", "Casa Darry",
    "Casa Deddings", "Casa Dustin", "Casa Fell", "Casa Flint", "Casa Footly",
    "Casa Grey", "Casa Grimm", "Casa Harte", "Casa Hayford", "Casa Hornwood",
    "Casa Mallister", "Casa Manderly", "Casa Massey", "Casa Merryweather",
    "Casa Mullendore", "Casa Perryn", "Casa Piper", "Casa Roote", "Casa Rowan",
    "Casa Royce", "Casa Smallwood", "Casa Staunton", "Casa Sunderland",
    "Casa Tarly", "Casa Vance", "Casa Vypren", "Casa Wode"
]

team_green = [
    "Casa Baratheon", "Casa Hightower", "Casa Lannister", "Casa Strong",
    "Casa Ambrose", "Casa Bourney", "Casa Butterwell", "Casa Crakehall",
    "Casa Fossoway", "Casa Graceford", "Casa Lefford", "Casa Leygood",
    "Casa Mooton", "Casa Norcross", "Casa Peake", "Casa Redwyne", "Casa Reyne",
    "Casa Risley", "Casa Rodden", "Casa Rosby", "Casa Roxton", "Casa Stokeworth",
    "Casa Swann", "Casa Swyft", "Casa Tarbeck", "Casa Thorne", "Casa Vance",
    "Casa Wylde"
]